package tagregister

import (
	"fmt"
	"sort"
	"strings"
)

// RenderRegister builds the tag-register.txt body (UTF-8, Unix newlines).
func RenderRegister(counts map[string]int, deps []Deprecation) string {
	var b strings.Builder
	b.WriteString("# Tag register (generated). Do not edit this file by hand.\n")
	b.WriteString("# Active tags come from content/**/*.md front matter \"tags\".\n")
	b.WriteString("# Deprecations: edit data/tag-deprecations.toml, then run: make tag-register\n")
	b.WriteString("\n")

	b.WriteString("## Active tags\n")
	b.WriteString("# Columns: tag<TAB>file_count (each file counts at most once per distinct tag)\n")
	type row struct {
		tag   string
		count int
	}
	var active []row
	for tag, n := range counts {
		if n <= 0 {
			continue
		}
		active = append(active, row{tag: tag, count: n})
	}
	sort.Slice(active, func(i, j int) bool {
		if active[i].count != active[j].count {
			return active[i].count > active[j].count
		}
		return active[i].tag < active[j].tag
	})
	for _, r := range active {
		b.WriteString(fmt.Sprintf("%s\t%d\n", r.tag, r.count))
	}

	b.WriteString("\n## Deprecated tags\n")
	b.WriteString("# Source: data/tag-deprecations.toml. Prefer \"to\" for new content instead of \"from\".\n")
	b.WriteString("# Columns: from<TAB>to<TAB>files_still_using_from\n")
	if len(deps) == 0 {
		b.WriteString("# (none)\n")
	} else {
		for _, d := range deps {
			n := counts[d.From]
			b.WriteString(fmt.Sprintf("%s\t%s\t%d\n", d.From, d.To, n))
		}
	}
	return b.String()
}
